book:
  title: "R for Data Science: Visualizations"
  reader-mode: true
  author: "Hadley Wickham"
  date: "5/9/2021"
  chapters:
    - index.qmd
    - data-visualize.qmd
    - layers.qmd
  page-footer:
    left: |
      The Solutions to Exercises for R for Data Science (2e) was written by
      Jabir Ghaffar, Davon Person, and Mine Çetinkaya-Rundel.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/mine-cetinkaya-rundel/r4ds-solutions/
  repo-branch: main
  repo-actions: [edit, issue]
format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
    author-meta: "Jabir Ghaffar, Davon Person, and Mine Çetinkaya-Rundel"
    callout-appearance: simple
ditor: visual
execute:
  freeze: auto
  
  
