project:
  type: book
  output-dir: _book

book:
  title: "r4ds-ggplot2"
  reader-mode: true
  author: "Hadley Wickham"
  downloads: [pdf, epub]
  date: "2023-11-13"
  sidebar:
    title: false
    style: docked
    background: primary
    foreground: light
    search: false
  navbar:
    background: primary
    foreground: light
    search: true
  chapters:
    - index.qmd
    - data-visualize.qmd
    - layers.qmd
  page-footer:
    left: |
      R for Data Science was written by Hadley Wickham
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/gurinina/r4ds-ggplot2/
  repo-branch: main



format:
  html:
    toc: true
    toc-location: left
    toc-depth: 2
    theme:
      cosmo
      r4ds.scss
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
    cover-image: images/koos10.png
  epub:
    cover-image: images/koos10.png

highlight-style: pygments
